[project]
name = "HW_4"
version = "0.1.0"
description = "HW_4 for the Python MSH5"
authors = [
    { name = "kara-victor" }
]

requires-python = "3.11"

dependencies = ["time", "threading", "multiprocessing"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
