[project]
name = "HW_1"
version = "0.1.0"
description = "HW_1 for the Python MSH5"
authors = [
    { name = "kara-victor" }
]

requires-python = "3.10.5"

dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
