[project]
name = "HW_3"
version = "0.1.0"
description = "HW_3 for the Python MSH5"
authors = [
    { name = "kara-victor" }
]

requires-python = "3.11"

dependencies = ["numpy"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
